onlinejudge/judge/urls.py
from django.urls import path

from . import views
app_name = 'judge'

urlpatterns = [
    path('judge/problem', views.view_problems, name='view_problems'),
    path('judge/problem/<int:problem_id>/', views.problem_detail, name='problem_detail'),

]

onlinejudge/onlinejudge/urls.py
from django.contrib import admin
from django.urls import include, path
from judge import views as jv
from users import views as uv

urlpatterns = [
    path('', uv.index),
    path('judge/', jv.intro),
    path('judge/problem', jv.view_problems),
    path('judge/<int:problem_id>/', jv.problem_detail),
    path('judge/add-problem/', jv.add_problem),
    path('judge/<int:problem_id>/judge/submit/', jv.submit),
    path('login', uv.loginuser),
    path('logout', uv.logoutuser),
    path('admin/', admin.site.urls),
]

onlinejudge/users/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views

urlpatterns = [
    path('', views.index, name="home"),
    path('login', views.loginuser, name="login"),
    path('logout', views.logoutuser, name="logout"),
]

onlinejudge/judge/models.py
from django.db import models

from django.contrib.auth.models import User


class Problem(models.Model):
    # problem_id = models.IntegerField(max_length=100)
    problem_name = models.CharField(max_length=100)
    problem_desc = models.CharField(max_length=500)
    diff = models.CharField(max_length=50)
    problem_solved = models.BooleanField(default=False)

    def __str__(self):
        return self.problem_name


class Testcases(models.Model):
    input = models.CharField(max_length=500)
    output = models.CharField(max_length=500)
    problem = models.ForeignKey(Problem, on_delete=models.CASCADE)

    def __str__(self):
        return self.input



LANGUAGES = (
                ("C", "GNU C"),
                ("CPP", "GNU C++"),
                )


class Submissions(models.Model):
    # STATUSES = (
    #     ("NT", "Not tested"),
    #     ("AC", "Accepted"),
    #     ("WA", "Wrong Answer")
    # )
    # submitter = models.ForeignKey(Coder, null=True, on_delete=models.CASCADE)
    # status = models.CharField(max_length=2, default="NT", choices=STATUSES)
    problem = models.ForeignKey(Problem, on_delete=models.CASCADE)
    verdict = models.CharField(max_length=50)
    timestamp = models.DateTimeField()
    code = models.CharField(max_length=1000)
    lang = models.CharField(max_length=4, default="C", choices=LANGUAGES)
    file = models.FileField(null=True, upload_to='solutions', max_length=1000)

    def __str__(self):
        return self.verdict


class Important(models.Model):
    problem = models.ForeignKey(Problem, on_delete=models.CASCADE)
    Imp_status = models.BooleanField(default=False)

    def __str__(self):
        return self.Imp_status
# Create your models here.

# Create your models here.

# Create your models here.

onlinejudge/users/models.py
from django.db import models

# Create your models here.

onlinejudge/judge/forms.py
from django import forms
from .models import Problem, Testcases, Submissions
from django.contrib.auth.models import User


class ProblemForm(forms.ModelForm):
    problem_name = forms.CharField()
    problem_desc = forms.CharField(widget=forms.Textarea)
    diff = forms.CharField()

    class Meta:
        model = Problem
        fields = ['problem_name', 'problem_desc', 'diff']


class SubmissionForm(forms.ModelForm):
    langs = [("C", "C"),  ("CPP", "C++"), ("JAVA", "Java"), ("PYTH", "python"), ("PYTH3", "python 3")]
    code = forms.CharField(widget=forms.FileInput)
    lang = forms.ChoiceField(choices=langs)
    file = forms.FileField()

    class Meta:
        model = Submissions
        fields = ['code', 'lang', 'file']

onlinejudge/judge/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.utils import timezone
from django.urls import reverse
from django.views import generic
import os, filecmp
# from judge.functions.functions import handle_uploaded_file

from .forms import ProblemForm, SubmissionForm
from .models import Problem, Submissions, Testcases


def intro(request):
    return render(request, 'base.html')


def view_problems(request):
    problems_list = Problem.objects.order_by('-problem_name')[:5]
    context = {'problems_list': problems_list}
    return render(request, 'prob.html', context)


def problem_detail(request, problem_id):
    prob = get_object_or_404(Problem, pk=problem_id)
    return render(request, 'detail.html', {'problem': prob})


def add_problem(request):
    if request.user.is_superuser:
        if request.method == 'POST':
            problem_form = ProblemForm(request.POST, request.FILES)
            if problem_form.is_valid():
                # save a new problem
                problem = problem_form.save()
                problem.save()
                # link the to the problem and save the test case to db
                return HttpResponseRedirect("/judge/problem")
        else:
            # instantiate a new ProblemForm and then render the addproblem page
            problem_form = ProblemForm()
            return render(request, "addprob.html", {"problem_form": problem_form})
        # if user is not logged in, throw him to a sign-in page
        # if not request.user.is_authenticated:
        #     return HttpResponseRedirect("http://127.0.0.1:8000/login")
        # else:


def submit(request, problem_id):
    if request.method == 'POST':
        sub_form = SubmissionForm(request.POST, request.FILES)
        if sub_form.is_valid():
            # handle_uploaded_file(request.POST, request.FILES)
            sub = sub_form.save()
            sub.problem = Problem.objects.get(code=problem_id)
            print(sub.problem.code)
            # sub.submitter = Coder.objects.get(user=request.user)
            # print(sub.submitter)
            sub.save()
            # evaluate_submission.delay(sub.id)
            return HttpResponse("Code Submitted!")
    else:
        sub_form = SubmissionForm()
        payload = {"sub_form": sub_form, "pid": problem_id}
        return render(request, "detail.html", payload)



# Create your views here.

onlinejudge/users/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth import logout, authenticate, login


def index(request):
    print(request.user)
    if request.user.is_anonymous:
        return redirect("/login")
    return render(request, 'prob.html')


def loginuser(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        print(username, password)

        # check if user has entered correct credentials
        user = authenticate(username=username, password=password)

        if user is not None:
            # A backend authenticated the credentials
            login(request, user)
            return redirect("/")

        else:
            # No backend authenticated the credentials
            return render(request, 'login.html')

    return render(request, 'login.html')


def logoutuser(request):
    logout(request)
    return redirect("/login")




# Create your views here.

onlinejudge/templates/addprob.html
<!--.log a {-->
<!--position: fixed;-->
<!--right: 0;-->
<!--top: 0;-->
<!--text-align: center;-->
<!--width: 150px;-->
<!--font-size: 18px;-->
<!--border: 2px solid #FF0000;-->

<!--}-->
{% block body_block %}
    <h2 style="text-align:center"> Add a problem </h2>
    <form id="ProblemForm" method="post" action="/judge/add-problem/"
        enctype="multipart/form-data">
        {% csrf_token %}
        {{ problem_form.as_p }}

        <input type="submit" name="submit" value = "add problem" />
    </form>
{% endblock %}

onlinejudge/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Online Judge</title>
</head>
<body>
<p>Online Judge!</p>
</body>
</html>

onlinejudge/templates/detail.html
<!DOCTYPE html>
<html>

<head>
<!--<title>CSS Template</title>-->
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
{
  box-sizing: border-box;
}

body {
  font-family: Arial, Helvetica, sans-serif;
}

/* Style the header */
header {
  background-color: #666;
  padding: 15px;
  text-align: center;
  font-size: 25px;
  color: white;
}

<!--/* Create two columns/boxes that floats next to each other */-->
<!--nav {-->
<!--  float: left;-->
<!--  width: 30%;-->
<!--  height: 300px; /* only for demonstration, should be removed */-->
<!--  background: #ccc;-->
<!--  padding: 20px;-->
<!--}-->

<!--/* Style the list inside the menu */-->
<!--nav ul {-->
<!--  list-style-type: none;-->
<!--  padding: 0;-->
<!--}-->

article {
  float: left;
  padding: 20px;
  width: 50%;
  background-color: #f1f1f1;
<!--  height: 300px; /* only for demonstration, should be removed-->
}

/* Clear floats after the columns */
section::after {
  content: "";
  display: table;
  clear: both;
}

<!--/* Style the footer */-->
<!--footer {-->
<!--  background-color: #777;-->
<!--  padding: 10px;-->
<!--  text-align: center;-->
<!--  color: white;-->
<!--}-->

/* Responsive layout - makes the two columns/boxes stack on top of each other instead of next to each other, on small screens */
@media (max-width: 600px) {
  nav, article {
    width: 100%;
    height: auto;
  }
}
</style>
</head>
<body>

<header>
  <h2> {{ problem.problem_name }} </h2>
</header>
<br/>
<section>
<p style="font-size: 20px"> {{ problem.problem_desc }} </p>
<!--</section>-->
<!--  <article>-->
<!--    <p>Input</p>-->

<!--    <p> {{ problem.input }} </p>-->
<!--    <p>Output</p>-->
<!--  </article>-->
</section>
<hr>
<div style="position: center;top: 100px; text-align: center">

    <h3> Submit Solution!</h3>

   <form id="submit_form" method = "post" action = "judge/submit/" class="ui fluid form"
        enctype = "multipart/form-data">
        {% csrf_token %}
        <p><label class="ui right pointing label basic blue">Language:</label>
        <select id="id_lang" name="lang" class="ui dropdown" >
			<option value="C">C</option>
			<option value="CPP">C++</option>
		</select></p>
<p><label for="id_code">Code:</label> <textarea cols="40" id="id_code" name="code" rows="10">
</textarea></p>
<div style="position: relative; font-size:18px;">
    <form action="/action_page.php">
        {% csrf_token %}
        {{ sub_form.as_p }}
  <input type="file" id="myFile" name="filename">
   <input type = "submit" name = "submit" value = "Submit"  class="ui button teal">
</form>
<!--        <input type = "submit" name = "submit" value = "Submit"  class="ui button teal">-->
</div>
    </form>

<script type="text/javascript">
	$('#id_lang')
	  .dropdown();
</script>
<!--<footer>-->
<!--  <p>Footer</p>-->
<!--</footer>-->
</div>
</body>
</html>

onlinejudge/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Logged in user</title>
</head>
<body>
   <h3> Welcome, {{request.user}}! </h3>

    <a href="/logout">Logout</a>
</body>
</html>

onlinejudge/templates/login.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">


    <style>
        html,
        body {
            height: 100%;

        }

        body {
        font-family: 'Montserrat', sans-serif;
            display: -ms-flexbox;
            display: flex;
            -ms-flex-align: center;
            align-items: center;

            padding-top: 40px;
            padding-bottom: 40px;
            background-color: #f5f5f5;
        }

        .form-signin {
            width: 100%;
            max-width: 330px;
            padding: 15px;
            margin: auto;
        }

        .form-signin .checkbox {
            font-weight: 400;
        }

        .form-signin .form-control {
            margin: 16px 3px;
            position: relative;
            box-sizing: border-box;
            height: auto;
            padding: 10px;
            font-size: 16px;
        }

        .form-signin .form-control:focus {
            z-index: 2;
        }

        .form-signin input[type="email"] {
            margin-bottom: -1px;
            border-bottom-right-radius: 0;
            border-bottom-left-radius: 0;
        }

        .form-signin input[type="password"] {
            margin-bottom: 10px;
            border-top-left-radius: 0;
            border-top-right-radius: 0;
        }

        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            -ms-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }
    </style>
    <!-- Custom styles for this template -->
    <link href="signin.css" rel="stylesheet">
</head>

<body class="text-center">
    <form class="form-signin" method="post" action="/judge/problem">
        {% csrf_token %}
        <img class="mb-4" src="https://www.freeiconspng.com/thumbs/login-icon/user-login-icon-14.png" alt="" width="72" height="72">
        <h1 class="h3 mb-3 font-weight-normal">USER LOGIN</h1>
        <label for="inputEmail" class="sr-only">Username</label>
        <input type="text" id="inputEmail" name="username" class="form-control" placeholder="Username" required
            autofocus>
        <label for="inputPassword" class="sr-only">Password</label>
        <input type="password" id="inputPassword" name="password" class="form-control" placeholder="Password" required>
        <div class="checkbox mb-3">
            <label>
                <input type="checkbox" value="remember-me"> Remember me
            </label>
        </div>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Login</button>
        <p class="mt-5 mb-3 text-muted">&copy; 2022</p>
    </form>
</body>

</html>

onlinejudge/templates/prob.html
<!DOCTYPE html>
<html>
<head>
      <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
<style>
table.t2{
border-collapse: collapse;
font_size: 15px;
  width: 50%;
  display:inline-table;
}
<!--td {-->
<!--  text-align: center;-->
<!--}-->
<!--td.a {-->
<!--text-align: left;-->
<!--}-->
table.t1{
border-collapse: collapse;
font_size: 15px;
  width: 50%;
  display:inline-table;
}
.log a {
position: fixed;
right: 0;
top: 0;
text-align: center;
width: 150px;
font-size: 18px;
border: 2px solid #FF0000;

}
.log1 a {
position: absolute;
right: 150px;
top: 0;
text-align: center;
width: 110px;
font-size: 18px;

}
.add {
            background-color: white;
            color: black;
            padding: 5px 10px;
            text-align: center;
            cursor: pointer;
        }
</style>
</head>
<body>
<!--{% if request.user.is_superuser %}-->
<!--<p>Welcome A</p>-->
<!--{% else %}-->
Welcome {{request.user}}
<!--{% endif %}-->
<div class="log">
    <a href="/logout">Logout</a>
    </div>
<!--{% if request.user.is_anonymous %}-->
<div class="log1">
    <a href="/judge/add-problem/">
        <button class="add" type="submit">
            Add Problem
        </button></a>
    </div>
<!--{% endif %}-->
</body>
{% if problems_list %}
 <table class="t1">
  <tr>
    <th style="width:80px">Problems</th>
    <th style="width:80px">Difficulty level</th>
    <th style="width:80px">Solved status</th>
  </tr>
        </table>
    <ol>
    {% for problem in problems_list %}
            <table class="t2">
  <tr>
      <td style="width:80px"><li><a href="/judge/{{ problem.id }}/">{{ problem.problem_name }} </a></li></td>
    <td align="center"; style="width:80px">{{problem.diff}}</td>
    <td align="center"; style="width:80px">{{ problem.problem_solved }}</td>
  </tr>
</table>
<!--        <li><a href="/judge/{{ problem.id }}/">{{ problem.problem_name }} </a>-->
<!--            {{problem.diff}} <h6> Problem solved status : {{ problem.problem_solved }} </h6></li>-->

    {% endfor %}
    </ol>
{% else %}
    <p>No problems are available.</p>
{% endif %}
</html>